### ISSUE TITLE
Lock-up (Mutex deadlock) on starting with network enabled

### ISSUE THREAD

**Issue by rubdos** [black-sheep-dev/harbour-quartermaster#1]
Hi! Thanks for this initiative!

My config:

```ini
[API]
external_url=https://ha.rubdos.be/
hostname=ha.rubdos.be
internal_url=https://ha.rubdos.be/
port=443
ssl=true

[APP]
tracking_modes=2
update_modes=7
websocket_notify=true

[DEVELOPER_MODE]
api_logging=false

[DEVICE]
name=Xperia 10

[HOMEZONE]
networks\1\identifier=/net/connman/service/wifi_3878625de747_536561726368696e67_managed_psk
networks\1\name=Searching
networks\size=1

[SENSORS]
autoupdate=true

[WEBHOOK_API]
encryption=false
```

```
(gdb) bt
#0  0xf6829fd0 in syscall () from /lib/libc.so.6
#1  0xf6a44e96 in QBasicMutex::lockInternal() () from /usr/lib/libQt5Core.so.5
#2  0xf6df97a2 in ?? () from /usr/lib/libQt5Network.so.5
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) info threads
  Id   Target Id                   Frame
* 1    LWP 22268 "harbour-quarter" 0xf6829fd0 in syscall () from /lib/libc.so.6
  2    LWP 22308 "QQmlThread"      0xf6791da4 in ?? () from /lib/libc.so.6
  3    LWP 22309 "gmain"           0xf6791da4 in ?? () from /lib/libc.so.6
  4    LWP 22310 "dconf worker"    0xf6791da4 in ?? () from /lib/libc.so.6
  5    LWP 22311 "gdbus"           0xf6791da4 in ?? () from /lib/libc.so.6
  6    LWP 22312 "QDBusConnection" 0xf6791da4 in ?? () from /lib/libc.so.6
  7    LWP 22319 "Qt bearer threa" 0xf6791da4 in ?? () from /lib/libc.so.6
  8    LWP 22326 "Thread (pooled)" 0xf66df364 in ?? () from /lib/libpthread.so.0
  9    LWP 22328 "Qt HTTP thread"  0xf66df364 in ?? () from /lib/libpthread.so.0
  10   LWP 22329 "QSGRenderThread" 0xf66df364 in ?? () from /lib/libpthread.so.0
  11   LWP 22337 "NemoThumbnailLo" 0xf66df364 in ?? () from /lib/libpthread.so.0
  12   LWP 22338 "QSGRenderThread" 0xf66df364 in ?? () from /lib/libpthread.so.0
  13   LWP 22339 "Qt HTTP thread"  0xf6829fd0 in syscall () from /lib/libc.so.6
```

Looks like thread 13 and 1 are locking on each other.

Probably some combination of options triggers this, but I figured I should report this as a bug.  Let me know if you need a trace of one of these threads with symbols, or whether you need anything else.

This occurs right when starting the applications, I only see the Ambience background appearing and literally nothing else.

**Comment by black-sheep-dev** [comment]
Thanks for your bug report!

Some questions:
- Which version of Sailfish OS you have? 4.0.1.48?
- Does only the latest version 0.1.19 has this issue (where I moved the entity list to main page)?

I have tried your settings and for me everything works as expected.

**Comment by rubdos** [comment]
4.0.1.48 indeed, but 0.1.18 also locks up (although that actually shows a title and loading icon).

I think it only happens when home, where I have a direct IPv6 connection to the HA server. Over 4G (which is v4-only), it doesn't happen.

**Comment by rubdos** [comment]
Not sure whether related or not: the WiFi networks that I define in zones seem to go away after a while (not after one restart, but after a few. It's strange)

**Comment by black-sheep-dev** [comment]
I have changed some connections from QNetworkManger related stuff. Maybe this helps...

**Comment by rubdos** [comment]
Still locking up on 0.21... it's even before it's asking for the Sailfish Secret authorization.

**Comment by rubdos** [comment]
I'm not sure whether this is still an issue; I have started using Quartermaster a while ago already now.
