### ISSUE TITLE
internal/external url configuration without port assumes 8123 without possibility to change

### ISSUE THREAD

**Issue by rubdos** [black-sheep-dev/harbour-quartermaster#22]
My home assistant is configured as follows:
```yaml
homeassistant:
  internal_url: "https://ha.rubdos.be/"
  external_url: "https://ha.rubdos.be/"
```
which has worked correctly before I started using Quartermaster.

Many weird things happen now.

If I want to register my device with `https://ha.rubdos.be/`, then QM appends `:8123`, which creates the invalid url `https://ha.rubdos.be/:8123`. It appears when you press next, see the "could not connect" text, and then go back: the field has changed.

If I manually append :443, I get to the next step. In the next step, the internal and external connections are preset to `https://ha.rubdos.be:8123`. Again, I manually change this to read 443, because otherwise QM tries to alter the URL to be invalid.

I can then proceed to enter my long-lived access token, get all tests to pass, see it show :443 for both URLs
![image](https://user-images.githubusercontent.com/1263440/119865619-25da8700-bf1c-11eb-9745-6ba544a3ecf5.png)

After that, I get into device registration, and get "Registration failed". Going back a bit and forward again to entering the LLAT, I get "Error connecting to Home Assistant API".

What's even more funky, is that I now added `:443` in the home assistant config, but I get the exact same problem. It seems like HA correctly assumes that it can leave out the `:443` port when sending the URL information, and then QM incorrectly assumes `:8123`.

My suggestion would be to entirely stop trying to fix the URL in the application code, and instead have the default UI component show `http://localhost:8123` as a reminder.

**Comment by rubdos** [comment]
By the way, if you want to test this against my install, send me a ping somewhere private and I'll make you an account.

**Comment by black-sheep-dev** [comment]
Hi, thanks for your report. I will check this. Maybe it was not the best  idea to try to fix the url at all without testing all possibilities 😩 .

**Comment by rubdos** [comment]
> Hi, thanks for your report. I will check this. Maybe it was not the best idea to try to fix the url at all without testing all possibilities weary .

Ah well. Currently trying with this applied:

```diff
index 335753b..2982000 100644
--- a/src/api/apiinterface.cpp
+++ b/src/api/apiinterface.cpp
@@ -95,8 +95,8 @@ void ApiInterface::getDiscoveryInfo(const QString &uri)
 {
     QString url = uri;

-    if (!url.contains(QRegExp(RegExp::PORT_INCLUDED)))
-        url.append(QStringLiteral(":8123"));
+    // if (!url.contains(QRegExp(RegExp::PORT_INCLUDED)))
+    //     url.append(QStringLiteral(":8123"));

     m_config->setInternalUrl(url);
     refreshStates();
diff --git a/src/api/serverconfig.cpp b/src/api/serverconfig.cpp
index bca2ef2..d3a8fec 100644
--- a/src/api/serverconfig.cpp
+++ b/src/api/serverconfig.cpp
@@ -41,8 +41,8 @@ void ServerConfig::setData(const QJsonObject &object)

     QString externalUrl = object.value(ApiKey::KEY_EXTERNAL_URL).toString();
     if (!externalUrl.isEmpty()) {
-        if (!externalUrl.contains(QRegExp(RegExp::PORT_INCLUDED)))
-            externalUrl.append(QStringLiteral(":8123"));
+        // if (!externalUrl.contains(QRegExp(RegExp::PORT_INCLUDED)))
+        //     externalUrl.append(QStringLiteral(":8123"));

         setExternalUrl(externalUrl);
     }
@@ -51,8 +51,8 @@ void ServerConfig::setData(const QJsonObject &object)
     QString internalUrl = object.value(ApiKey::KEY_INTERNAL_URL).toString();

     if (!internalUrl.isEmpty()) {
-        if (!internalUrl.contains(QRegExp(RegExp::PORT_INCLUDED)))
-            internalUrl.append(QStringLiteral(":8123"));
+        // if (!internalUrl.contains(QRegExp(RegExp::PORT_INCLUDED)))
+        //     internalUrl.append(QStringLiteral(":8123"));

         setInternalUrl(internalUrl);
```

Seems like it's now very finnicky on trailing slashes, so maybe one part that needs URL-fixing is to trim the final slash on both internal and external (since you append it later).

I've just been able to register with the above patch and a config without trailing slashes, but *with* specifying the ports:

```yaml
homeassistant:
  internal_url: "https://ha.rubdos.be:443"
  external_url: "https://ha.rubdos.be:443"
```

During the registration, the internalUrl and externalUrl are shown in input fields, but those inputs don't really seem to influence everything until the end (ie., device registration seems not to take them into account, and the config gets overwritten with whatever HA itself provides).

Does all of this make sense to you? :-)

Either way, thanks a *lot* for your application. Very much appreciated :heart:

**Comment by black-sheep-dev** [comment]
Ok...I was faster. New release is out that hopefully fixes your issue. The app will not replace any port in the url.

**Comment by rubdos** [comment]
I suspect the issue with the double slash (internal_url + "/api/..." becomes "ha.rubdos.be//api") is still relevant though.

**Comment by black-sheep-dev** [comment]
Ok. I will fix that too.

**Comment by rubdos** [comment]
Thanks! I now noticed that I get the setup wizard on every start, but I'll have a look at why that is. Feel free to close when you have the `//` thing done! I'll open something new when necessary (and I'll have a look at my other issue too, whether it still applies).

**Comment by black-sheep-dev** [comment]
Hopefully this is not the Sailfish Secret Thing. I ran in this trouble when compiled in Debug Mode and created the Collection the first time. Then the release binary has no access to the collection anymore.

**Comment by rubdos** [comment]
> Hopefully this is not the Sailfish Secret Thing. I ran in this trouble when compiled in Debug Mode and created the Collection the first time. Then the release binary has no access to the collection anymore.

Ah that's probably it then, because I'm running from CLI and a debug build indeed.

**Comment by rubdos** [comment]
I'm not sure whether this is still an issue; I have started using Quartermaster a while ago already now.
